# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb74f74d7d7dc153f5984b8d41ef636fe9ef289afcaaf62eeb0be1657b0851b3060b9e5b2ad499ee42938da019494b0c60cc90271c783d840fe302a94c75a04e

test:
  secret_key_base: 81c8806f64ef23de5f2d01949fede051c8b84653fd8964e8e8b594e6a63a50e6e8f9bae2dd6d3aaac1f1a466c93e7cc371cae6121464dd91f058b810adf75f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
